const journeys = [
  ["I lost something", "Report an item and receive a private reference number.", "/report-lost", "Start a lost report"],
  ["I found something", "Tell the institution what you found so it can be secured.", "/report-found", "Report a found item"],
  ["Check my case", "Use your reference and phone number to see the latest update.", "/claim-status", "Check case status"],
];

export default function Home() {
  return <main className="public-shell"><nav className="public-nav"><a className="brand" href="/"><span className="brand-mark">+</span>foundry360</a><div><a href="/claim-status">Check a case</a><a className="nav-login" href="/login">Staff login</a></div></nav><section className="public-hero"><div><p className="eyebrow">Lost property, handled properly</p><h1>Find your way back to what matters.</h1><p className="hero-copy">Foundry360 connects people with the institution holding their lost property, while keeping identity and item details private.</p><div className="hero-actions"><a className="primary" href="/report-lost">Report something lost</a><a className="secondary" href="/report-found">Report something found</a></div></div><div className="hero-signal"><span className="signal-dot"/><b>Institution-secured</b><small>Trusted by participating desks in Kenya</small><div className="signal-line"/><small>One reference. Clear updates. Verified handover.</small></div></section><section className="journeys"><p className="eyebrow">What brings you here?</p><h2>Choose a secure starting point</h2><div className="journey-grid">{journeys.map(([title, copy, href, action], index) => <a className="journey-card" href={href} key={title}><span className="journey-number">0{index + 1}</span><h3>{title}</h3><p>{copy}</p><b>{action} →</b></a>)}</div></section><footer className="public-footer"><span>Foundry360 for institutions and their communities</span><span>Kenya · Privacy-first by design</span></footer></main>;
}
