# Generated by Django 5.1.15 on 2026-09-08 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('private_description', models.TextField()),
                ('status', models.CharField(choices=[('STORED', 'Stored'), ('MATCHED', 'Matched'), ('CLAIM_PENDING', 'Claim pending'), ('RETURNED', 'Returned'), ('DISPOSED', 'Disposed')], default='STORED', max_length=20)),
                ('restricted', models.BooleanField(default=False)),
                ('found_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='found_items', to='core.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='found_items', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=60)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='core.founditem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='core.organization')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_bins', to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='founditem',
            name='storage_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='found_items', to='core.storagebin'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_location_per_org'),
        ),
        migrations.AddIndex(
            model_name='custodyevent',
            index=models.Index(fields=['organization', 'created_at'], name='core_custod_organiz_65ef42_idx'),
        ),
        migrations.AddConstraint(
            model_name='storagebin',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_bin_per_org'),
        ),
        migrations.AddIndex(
            model_name='founditem',
            index=models.Index(fields=['organization', 'status'], name='core_foundi_organiz_852f38_idx'),
        ),
        migrations.AddIndex(
            model_name='founditem',
            index=models.Index(fields=['organization', 'category'], name='core_foundi_organiz_28e4d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='founditem',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='unique_reference_per_org'),
        ),
    ]
