# Generated by Django 5.1.15 on 2026-09-08 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.CharField(max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimant_name', models.CharField(max_length=180)),
                ('claimant_phone', models.CharField(max_length=40)),
                ('evidence', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('EVIDENCE_REQUIRED', 'Evidence required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COLLECTED', 'Collected')], default='SUBMITTED', max_length=24)),
                ('collection_pin_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.founditem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DisposalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('AUCTION', 'Auction'), ('DONATION', 'Donation'), ('DESTRUCTION', 'Destruction'), ('RETURNED_TO_AUTHORITY', 'Returned to authority')], max_length=32)),
                ('notice_issued_at', models.DateTimeField(blank=True, null=True)),
                ('disposed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_disposals', to=settings.AUTH_USER_MODEL)),
                ('found_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_event', to='core.founditem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_events', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32)),
                ('claimant_name', models.CharField(max_length=180)),
                ('claimant_phone', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('last_seen_location', models.CharField(max_length=180)),
                ('lost_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lost_reports', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_suggestions', to='core.founditem')),
                ('lost_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_suggestions', to='core.lostreport')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_suggestions', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ORG_ADMIN', 'Organization admin'), ('SUPERVISOR', 'Supervisor'), ('OFFICER', 'Officer'), ('VIEWER', 'Viewer')], default='OFFICER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], max_length=12)),
                ('recipient', models.CharField(max_length=180)),
                ('template', models.CharField(max_length=80)),
                ('provider_id', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='QUEUED', max_length=12)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(max_length=40)),
                ('checkout_request_id', models.CharField(blank=True, max_length=180)),
                ('receipt_number', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PreventativeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('owner_phone', models.CharField(blank=True, max_length=40)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preventative_tags', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='RetentionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(max_length=80)),
                ('scheduled_for', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retention_jobs', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('IN_TRANSIT', 'In transit'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='core.founditem')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='core.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='core.organization')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='core.location')),
            ],
        ),
        migrations.AddIndex(
            model_name='lostreport',
            index=models.Index(fields=['organization', 'status'], name='core_lostre_organiz_ac2788_idx'),
        ),
        migrations.AddIndex(
            model_name='lostreport',
            index=models.Index(fields=['organization', 'category'], name='core_lostre_organiz_f19e29_idx'),
        ),
        migrations.AddConstraint(
            model_name='lostreport',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='unique_lost_reference_per_org'),
        ),
        migrations.AddConstraint(
            model_name='matchsuggestion',
            constraint=models.UniqueConstraint(fields=('found_item', 'lost_report'), name='unique_match_pair'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_membership_per_org'),
        ),
        migrations.AddConstraint(
            model_name='preventativetag',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_preventative_tag_per_org'),
        ),
    ]
