# Generated by Django 5.1.15 on 2026-09-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_claim_disposalevent_lostreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='location',
            name='is_receiving_point',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='kind',
            field=models.CharField(choices=[('SECURITY_DESK', 'Security desk'), ('RECEPTION', 'Reception'), ('REGISTRY', 'Registry'), ('PROPERTY_STORE', 'Property store')], default='SECURITY_DESK', max_length=24),
        ),
        migrations.AddField(
            model_name='location',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
